### ISSUE TITLE
Doesn't work in cordova

### ISSUE THREAD

**Issue by ihsansatriawan** [keppelen/react-facebook-login#114] opened 2017-02-28 07:53 UTC
Hi...i  have react apps in browser and cordova with same code, i interest use this library, but when i try in browser, everything is good, but in cordova, there is error `GET file://connect.facebook.net/en_US/all.js net::ERR_FILE_NOT_FOUND`

thx

**Comment by styfle** [comment] 2017-03-14 00:14
Looks like the problem is that all the external files leave off the [protocol](https://github.com/keppelen/react-facebook-login/blob/dd66471a5a4b993a88ac67a7870dcc3f7dfc7a10/src/facebook.js#L123)

I'm sure this can be fixed with a PR changing these to `https://` prefix.

**Closed** 2017-05-04 18:56 UTC

**Comment by imjared** [comment] 2018-09-06 19:17
Looks like this issue needs to be updated here as well: https://github.com/keppelen/react-facebook-login/blob/master/src/facebook.js#L192
